import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { initialize } from '../ui/app.js';
import { fixtureDocument, settle } from './control-page-dom-helper.mjs';

test('control page controller with deterministic DOM fixture (not browser visual QA)',async t=>{
 const names=['document','window','location','history','fetch','confirm','setInterval'],previous=Object.fromEntries(names.map(name=>[name,globalThis[name]]));
 const document=fixtureDocument(await fs.readFile(new URL('../ui/index.html',import.meta.url),'utf8')),$=id=>document.getElementById(id),calls=[],confirmations=[],order=[];let approved=true,hold=null,failCreation=false; const rootTemplate = { tools:['searchFiles','capabilities','readFile'], directories:[{path:'',read:true,write:false}] };
 let server={ok:true,status:{id:'servant',peers:[{id:'remote',connected:true}],active:0,policyEpoch:1,durable:true,transport:'TLSv1.3',unknownIncoming:1,unknownOutgoing:0},permissions:{epoch:1,revoked:[],effectivePolicy:{grants:{master:{workspace:'/work',tools:['readFile','writeFile'],directories:[{path:'docs',read:true,write:false}],maxConcurrent:1,maxTimeoutMs:2000,maxReadBytes:4096,workspaceProvisioning:{roots:{projects:{path:'/approved-projects',maxWorkspaces:8,grant:structuredClone(rootTemplate)}}}}}}},incoming:{records:[{masterId:'master',taskId:'uncertain',state:'unknown',tool:'writeFile'}]},outgoing:{records:[]},jobs:{jobs:[{jobId:'job1',masterId:'master',taskId:'start1',state:'unknown',command:'test'}]},identity:{nodeId:'servant',trustedPeers:[{id:'master',pins:['a'.repeat(64)]}]},workspaces:{revision:0,bindings:[]}};
 globalThis.document=document;globalThis.window={addEventListener(){}};globalThis.location={hash:'#token=one-use-test',pathname:'/'};globalThis.history={replaceState(){order.push('scrub');}};globalThis.confirm=message=>{confirmations.push(message);return approved;};globalThis.setInterval=()=>0;
 globalThis.fetch=async(route,options={})=>{order.push(route);const value=options.body?JSON.parse(options.body):undefined;calls.push({route,value});let data;
  if(route==='/api/session')data={ok:true,csrf:'fixture-csrf',expiresAt:'2030-01-01'};
  else if(route==='/api/state')data=structuredClone(server);
  else if(route==='/api/logout')data={ok:true};
  else if(route==='/api/logs')data={ok:true,records:[{timestamp:'2026-10-01',event:'task_finished',masterId:'master',taskId:'task1',state:'failed',code:'TASK_DENIED'}]};
  else if(route==='/api/command'){
   if(hold)await hold; if(value.command==='createWorkspace'&&failCreation){failCreation=false;throw new Error('fixture network interruption');}
   if(value.command==='setPolicy'){server.permissions.effectivePolicy=value.policy;server.permissions.epoch++;server.status.policyEpoch++;}
   if(value.command==='revoke'){delete server.permissions.effectivePolicy.grants[value.masterId];server.permissions.revoked.push(value.masterId);server.permissions.epoch++;server.status.policyEpoch++;}
   let workspaceResult;
   if(value.command==='remoteWorkspaces') workspaceResult={workspaces:[{id:'existing',name:'existing',state:'ready',kind:'configured',tools:['readFile'],filesystem:{mode:'scoped',directories:[{path:'',read:true,write:false}]}},{id:'broken',name:'broken',state:'unknown',kind:'provisioned'}],creationRoots:[{id:'projects',maxWorkspaces:8,used:0,remaining:8,tools:['readFile'],filesystem:{mode:'scoped',directories:[{path:'',read:true,write:false}]}}]};
   if(value.command==='setWorkspaceAutoProvision'){server.workspaces.autoProvision=[{...value}];server.workspaces.revision++;workspaceResult=server.workspaces;}
   if(value.command==='ensureWorkspaceBinding'){if(!server.workspaces.bindings.length){server.workspaces.bindings.push({logicalWorkspaceId:value.logicalWorkspaceId,peerId:value.peerId,workspaceId:'ws_created'});server.workspaces.revision++;}workspaceResult=server.workspaces.bindings[0];}
   if(value.command==='bindWorkspace'){server.workspaces.bindings=[{logicalWorkspaceId:value.logicalWorkspaceId,peerId:value.peerId,workspaceId:value.workspaceId}];server.workspaces.revision++;workspaceResult=server.workspaces;}
   if(value.command==='unbindWorkspace'){server.workspaces.bindings=[];server.workspaces.revision++;workspaceResult=server.workspaces;}
   if(value.command==='createWorkspace'){server.workspaces.bindings=[{logicalWorkspaceId:value.logicalWorkspaceId,peerId:value.peerId,workspaceId:'ws_manual'}];server.workspaces.revision++;workspaceResult={workspace:{id:'ws_manual'},binding:server.workspaces.bindings[0],revision:server.workspaces.revision};}
   data={ok:true,result:workspaceResult??(value.command==='jobOutput'?{jobId:value.jobId,stream:value.stream,offset:value.offset,text:'<unsafe output>',nextOffset:value.offset+4,totalBytes:8,eof:value.offset+4>=8}:value.command==='taskStatus'?{taskId:value.taskId,state:'unknown'}:{applied:true})};
  }else throw new Error('Unexpected route '+route);
  return {ok:true,status:200,json:async()=>data};
 };
 try{
  initialize();await settle();
  await t.test('bootstrap fragment scrubbed before request; authenticated Chinese relationships render',()=>{assert.equal(order[0],'scrub');assert.equal($('workspace').hidden,false);assert.match($('peers').textContent,/servant → remote/);assert.match($('incoming-peers').textContent,/master → servant/);assert.match($('grant-list').textContent,/docs.*只读/);assert.equal($('unknown-count').textContent,'2');assert.equal($('directory-mode').value,'scoped');});
  await t.test('editor uses actual rules; cancelled row removal keeps deny/allow inheritance unchanged',()=>{$('grant-list').querySelector('button').dispatch('click');assert.equal($('grant-peer').readOnly,true);assert.equal($('directory-rules').children.length,1);approved=false;$('directory-rules').querySelector('button').dispatch('click');assert.equal($('directory-rules').children.length,1);assert.match(confirmations.at(-1),/恢复父目录继承/);approved=true;});
  await t.test('repeated save is gated; advanced limits preserved and explicit review includes directories',async()=>{const path=$('directory-rules').querySelector('[data-rule-path]');path.value='work';path.dispatch('input');let release;hold=new Promise(resolve=>release=resolve);const before=calls.filter(c=>c.value?.command==='setPolicy').length;$('grant-form').dispatch('submit');$('grant-form').dispatch('submit');await settle();assert.equal(calls.filter(c=>c.value?.command==='setPolicy').length,before+1);assert.match(confirmations.at(-1),/目录：[\s\S]*work：只读/);release();hold=null;await settle();assert.equal(server.permissions.effectivePolicy.grants.master.maxReadBytes,4096);assert.deepEqual(server.permissions.effectivePolicy.grants.master.workspaceProvisioning.roots.projects.grant,rootTemplate,'unrelated edit must preserve exact provisioning template hash');assert.equal($('save-grant').disabled,false);assert.match($('notice').textContent,/持久保存/);});
  await t.test('background refresh preserves unsaved draft and rejects stale epoch',async()=>{$('grant-workspace').value='/changed';$('grant-workspace').dispatch('input');server.permissions.epoch++;server.status.policyEpoch++;$('refresh').dispatch('click');await settle();assert.equal($('grant-workspace').value,'/changed');assert.equal($('policy-conflict').hidden,false);assert.equal($('save-grant').disabled,true);const before=calls.length;$('grant-form').dispatch('submit');await settle();assert.equal(calls.length,before);assert.match($('notice').textContent,/权限版本已变化/);$('discard-grant').dispatch('click');assert.equal($('grant-workspace').value,'/work');assert.equal($('policy-conflict').hidden,true);});
  await t.test('structured servant creation roots preserve template and do not auto-enable create tools',async()=>{assert.equal($('owner-creation-roots').children.length,1);assert.equal($('owner-create-enabled').checked,false);$('owner-create-enabled').checked=true;$('owner-create-enabled').dispatch('input');assert.equal(document.querySelectorAll('[name=tool]').find(n=>n.value==='workspaceCreate').checked,true);$('owner-list-enabled').checked=true;$('owner-list-enabled').dispatch('input');$('grant-form').dispatch('submit');await settle();assert.equal(server.permissions.effectivePolicy.grants.master.tools.includes('workspaceCreate'),true);assert.deepEqual(server.permissions.effectivePolicy.grants.master.workspaceProvisioning.roots.projects.grant,rootTemplate);});
  await t.test('workspace catalog shows unavailable entries but only ready workspaces can be bound',async()=>{$('logical-workspace').value='project-alpha';$('workspace-context-form').dispatch('submit');await settle();assert.equal($('workspace-catalog').hidden,false);assert.deepEqual($('existing-workspace').options.map(o=>o.value),['existing']);const broken=$('catalog-summary').children.find(n=>n.textContent.includes('broken'));assert.match(broken.textContent,/待核对/);assert.doesNotMatch(broken.textContent,/整个工作区/);assert.equal(server.workspaces.bindings.length,0);});
  await t.test('saving auto-preparation is distinct from creating, while ensure establishes and reuses binding',async()=>{$('auto-enabled').checked=true;$('workspace-auto-form').dispatch('submit');await settle();assert.equal(server.workspaces.bindings.length,0);assert.equal(server.workspaces.autoProvision[0].enabled,true);assert.match($('workspace-result').textContent,/尚未因此创建/);$('ensure-workspace').dispatch('click');await settle();assert.equal(server.workspaces.bindings.length,1);assert.match($('workspace-bindings').textContent,/ws_created/);$('ensure-workspace').dispatch('click');await settle();assert.equal(server.workspaces.bindings.length,1);assert.equal(calls.filter(c=>c.value?.command==='createWorkspace').length,0,'system ensure is independent from manual create command');});
  await t.test('binding revisions are frozen; unbinding retains files and changing context invalidates catalog',async()=>{server.workspaces.revision++;$('refresh').dispatch('click');await settle();assert.equal($('workspace-conflict').hidden,false);assert.equal($('bind-workspace').disabled,true);const before=calls.length;$('workspace-bind-form').dispatch('submit');await settle();assert.equal(calls.length,before);$('workspace-context-form').dispatch('submit');await settle();$('workspace-bindings').querySelector('button').dispatch('click');await settle();assert.equal(server.workspaces.bindings.length,0);assert.match(confirmations.at(-1),/文件不会删除/);assert.ok(!calls.some(c=>['deleteWorkspace','deleteFile'].includes(c.value?.command)));$('logical-workspace').value='another';$('logical-workspace').dispatch('input');assert.equal($('workspace-catalog').hidden,true);assert.equal($('ensure-workspace').disabled,true);});
  await t.test('manual creation has a stable request identity after uncertain network result and only approved roots',async()=>{$('logical-workspace').value='manual-project';$('workspace-context-form').dispatch('submit');await settle();$('create-workspace-name').value='feature-one';failCreation=true;$('workspace-create-form').dispatch('submit');await settle();assert.match($('notice').textContent,/请求结果未确认/);const first=calls.filter(c=>c.value?.command==='createWorkspace').at(-1).value;assert.equal(first.rootId,'projects');$('refresh').dispatch('click');await settle();$('workspace-create-form').dispatch('submit');await settle();const last=calls.filter(c=>c.value?.command==='createWorkspace').at(-1).value;assert.equal(last.creationRequestId,first.creationRequestId);assert.equal($('create-workspace-name').value,'');assert.match($('workspace-result').textContent,/已创建并绑定/);});
  await t.test('selection does not execute; recovery needs explicit submit and evidence',async()=>{const before=calls.length;$('task-rows').querySelector('button').dispatch('click');assert.equal(calls.length,before);assert.equal($('task-direction').value,'incoming');$('task-action').value='reconcile';$('task-action').dispatch('change');assert.equal($('task-reconcile-fields').hidden,false);$('task-form').dispatch('submit');await settle();assert.equal(calls.length,before);assert.match($('notice').textContent,/证据/);$('task-action').value='status';$('task-action').dispatch('change');$('task-form').dispatch('submit');await settle();assert.match($('task-result-summary').textContent,/待核对/);});
  await t.test('job output pagination and target changes cannot reuse another job cursor',async()=>{$('job-rows').querySelector('button').dispatch('click');$('job-action').value='jobOutput';$('job-action').dispatch('change');$('job-form').dispatch('submit');await settle();assert.equal($('job-output-text').textContent,'<unsafe output>');assert.equal($('job-next-page').disabled,false);$('job-next-page').dispatch('click');await settle();assert.equal(calls.filter(c=>c.value?.command==='jobOutput').at(-1).value.offset,4);assert.equal($('job-next-page').disabled,true);$('job-id').value='different';$('job-id').dispatch('input');assert.equal($('job-output-panel').hidden,true);assert.equal($('job-next-page').disabled,true);});
  await t.test('logs render structured metadata and search operates on loaded rows',async()=>{document.querySelectorAll('[data-view]').find(b=>b.dataset.view==='logs').dispatch('click');await settle();assert.match($('log-rows').textContent,/task_finished/);$('log-search').value='no-match';$('log-search').dispatch('input');assert.match($('log-rows').textContent,/没有符合/);});
  await t.test('logout clears sensitive result/grant DOM and returns to owner gate',async()=>{$('logout').dispatch('click');await settle();assert.equal($('workspace').hidden,true);assert.equal($('login').hidden,false);assert.equal($('policy-json').textContent,'');assert.equal($('task-result').textContent,'');assert.equal($('job-output-text').textContent,'');assert.equal($('directory-rules').children.length,0);assert.equal($('owner-token').value,'');});
 }finally{for(const name of names){if(previous[name]===undefined)delete globalThis[name];else globalThis[name]=previous[name];}}
});
